// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmcMAV-3vGvESvWi3yDS4vMNV7mqrXcYM',
    appId: '1:248524051938:web:f4a8cb5703fcee8a3415bb',
    messagingSenderId: '248524051938',
    projectId: 'smartspend-a6ba5',
    authDomain: 'smartspend-a6ba5.firebaseapp.com',
    storageBucket: 'smartspend-a6ba5.firebasestorage.app',
    measurementId: 'G-1PYZ29XTS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnK55V5prsoJjsjhciKX-0LyVQCXK9ekk',
    appId: '1:248524051938:android:93fa8cee673f94e73415bb',
    messagingSenderId: '248524051938',
    projectId: 'smartspend-a6ba5',
    storageBucket: 'smartspend-a6ba5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5i_bOeJx6fr0kl8SsjfU25nx-kYb15dM',
    appId: '1:248524051938:ios:a853f4ccda5360f03415bb',
    messagingSenderId: '248524051938',
    projectId: 'smartspend-a6ba5',
    storageBucket: 'smartspend-a6ba5.firebasestorage.app',
    iosBundleId: 'com.example.smartspend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5i_bOeJx6fr0kl8SsjfU25nx-kYb15dM',
    appId: '1:248524051938:ios:a853f4ccda5360f03415bb',
    messagingSenderId: '248524051938',
    projectId: 'smartspend-a6ba5',
    storageBucket: 'smartspend-a6ba5.firebasestorage.app',
    iosBundleId: 'com.example.smartspend',
  );
}
